In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['G:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'G:/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['G:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'G:/anaconda3\\Library\\include']
la

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
z = np.zeros((10,10))
z.size * z.itemsize

800

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [10]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
z = np.arange(50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [14]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
z = [1, 2, 0, 0, 4, 0]
np.nonzero(z)

(array([0, 1, 4], dtype=int64),)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.random((3, 3, 3))

array([[[0.34702557, 0.21751716, 0.28609214],
        [0.73390893, 0.52757168, 0.86985868],
        [0.88229575, 0.89440197, 0.54999409]],

       [[0.82183258, 0.80338611, 0.4781456 ],
        [0.14918154, 0.20518607, 0.42049413],
        [0.58972292, 0.3601239 , 0.11520717]],

       [[0.24525752, 0.4469638 , 0.45318351],
        [0.91320341, 0.31897245, 0.69772203],
        [0.50362029, 0.53984043, 0.91041128]]])

In [21]:
z = np.random.random((10,10))
print("最大值:%s" % z.max())
print("最小值:%s" % z.min())

最大值:0.9994280403333841
最小值:0.006440728496846959


In [22]:
z = np.random.random(30)
z.mean()

0.44535488990081334

In [23]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
z = np.ones((10,10))
np.pad(z, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
0 * np.nan

nan

In [27]:
np.nan == np.nan

False

In [29]:
np.inf > np.nan

False

In [30]:
np.nan - np.nan

nan

In [33]:
0.3 == 3 * 0.1

False

In [42]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [46]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [47]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [50]:
z = np.random.random((5,5))
zmax = z.max()
zmin = z.min()
z = (z-zmin)/(zmax-zmin)
z

array([[0.34140167, 0.02944638, 0.93475807, 0.        , 0.31000368],
       [0.66160558, 1.        , 0.84038446, 0.0882473 , 0.94591634],
       [0.82015842, 0.99656558, 0.09768769, 0.82029632, 0.21667519],
       [0.12836834, 0.72325262, 0.63714214, 0.40911481, 0.39709153],
       [0.95599883, 0.20759055, 0.8998288 , 0.7042081 , 0.48247714]])

In [52]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
color

G:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [54]:
z = np.dot(np.ones((5,3)), np.ones((3, 2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [58]:
z = np.arange(11)
z[(z>3)&(z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [59]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [64]:
z = np.arange(5)
z ** z

array([  1,   1,   4,  27, 256], dtype=int32)

In [65]:
2 << z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [67]:
z <- z

array([False, False, False, False, False])

In [68]:
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [69]:
z/1/1

array([0., 1., 2., 3., 4.])

In [70]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [71]:
np.array(0) / np.array(0)

G:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [72]:
np.array(0) // np.array(0)

G:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [75]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [76]:
Z = np.random.uniform(-10,+10,10)
print(Z)
np.copysign(np.ceil(np.abs(Z)), Z)

[ 8.9429649  -7.96887364 -2.84649559  3.79666738 -3.84700695 -5.24995324
  9.28976492  8.0799362  -7.12986662  3.43353232]


array([ 9., -8., -3.,  4., -4., -6., 10.,  9., -8.,  4.])

In [79]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(Z1,Z2)
np.intersect1d(Z1, Z2)

[0 1 8 0 5 5 5 2 5 0] [1 9 0 2 6 7 7 9 9 5]


array([0, 1, 2, 5])

In [82]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0
Z

array([inf])

In [86]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [89]:
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2020-04-19 2020-04-20 2020-04-21


In [91]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [92]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [93]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [94]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [95]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])